### ISSUE TITLE
Error when trying to delete marker

### ISSUE THREAD

**Issue by rndmh3ro** [YunoHost-Apps/owntracks_ynh#2]
When I try to delete a marker in the webfrontend, the requests gets a 500 error with the following error message in the php-log:
```
[26-Feb-2018 21:20:36] WARNING: [pool owntracks] child 10532 said into stderr: "NOTICE: PHP message: PHP Parse error:  syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) in /var/www/owntracks/rpc.php on line 20"
```

However I don't know if that's a problem with the yunohost app or with owntracks.

**Comment by tituspijean** [comment]
It is a problem with Owntracks. Can you try to manually replace line 20 of `rpc.php` with this

```
 $sql = "DELETE FROM ".$_config['sql_prefix']."locations
                      WHERE user = $_SERVER['PHP_AUTH_USER'] AND epoch = ?";
              $stmt = $mysqli->prepare($sql);
```
Basically there was a line break in the $stmt command which php/sql does not like. Upon your testing I will push an update on my fork of Owntracks.

**Comment by tituspijean** [comment]
FYI, it works for me on my server.

**Comment by tituspijean** [comment]
Oh, that was not true, there were still a typo.
