### ISSUE TITLE
Cannot connect iOS app

### ISSUE THREAD

**Issue by navanchauhan** [YunoHost-Apps/owntracks_ynh#20]
```
error HTTP Response 302 The operation couldn’t be completed. (HTTP Response error 302.) {
}
```
Configuration:

![image](https://user-images.githubusercontent.com/29234112/139635478-a7d2c96d-76be-4b43-b348-014a299e6573.png)

**Comment by angryfrenchguy** [comment]
same

**Comment by navanchauhan** [comment]
Solved it by adding the OwnTracks Permission to Visitors group

[Relevant Comment](https://github.com/YunoHost-Apps/owntracks_ynh/issues/23#issuecomment-1040273982)

Will look at the code tomorrow to see which exact endpoints we can push to an API flag and allow that for all visitors
