### ISSUE TITLE
HTTP Status 200, JsonParseException

### ISSUE THREAD

**Issue by elbubar** [YunoHost-Apps/owntracks_ynh#23]
### Describe the bug

*HTTP Status 200, JsonParseException*

### Context

- Hardware: *Kimsufi dedicated server*
- YunoHost version: 4.3.4.2 (stable)
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: Keep using registrar MX Plan 
- Using, or trying to install package version/branch: 0.1~ynh10

### Steps to reproduce

- *Create a domain name*
- *Get Let's Encrypt cert*
- *Install Owntracks via webadmin, settings as redirected to https://tracks.XXXXXXX.net*
- *Install the Android App*
- *Follow YNH how'to* Set connection as https://Domain/path/record.php

### Expected behavior

*Getting positions registered in the app*

### Logs

*No Logs*

The how to for YNH installation and link with mobile device says that the server address shall be : Host: https://DOMAIN/PATH/record.php

But it's not working and gets HTTP 200.

On the official documentation, we shall redirect to Host: https://DOMAIN/pub which is different, but not working neither...

Many thanks for your support on setting up correctly the app on android.

**Comment by akoshpinter** [comment]
Hi,

I had the same issue, adding visitor user to the permissions (i.e. making OwnTracks publicly available) solves the issue... Meaning, the HTTP request from the application is not doing the authentication correctly (the request is redirected to SSO of Yunohost).

**Comment by rob-hills** [comment]
I am having the same issue as reported here.

However, the workaround suggested [above](https://github.com/YunoHost-Apps/owntracks_ynh/issues/23#issuecomment-1040273982) doesn't work for me.  It gets rid of the error from the client app log, but still nothing appears on the map when I log in to my YunoHost server.

**Comment by amaurym** [comment]
Same as @rob-hills, after making OwnTracks public, no more error in logs, but nothing appears on map.
