### ISSUE TITLE
Purpose of WebUI

### ISSUE THREAD

**Issue by jose1711** [YunoHost-Apps/owntracks_ynh#24]
### Describe the bug

Please what is the point of a WebUI? It does display a scrollable map (with Paris hardcoded as a base location) but basically that's it. Is there anything I am missing?

**Comment by tituspijean** [comment]
> Please what is the point of a WebUI?

How would you prefer displaying your data?

> Is there anything I am missing?

Reading the README and Owntracks documentation, I guess.

**Comment by jose1711** [comment]
Thank you. That means I really should get a marker and/or track displayed there. I did read the README - it only details the configuration of a mobile client and that indeed works - I can see how the entries are being added to MySQL db. I could not find anything regarding WebUI in booklet - could be because the frontend fork is no longer supported by upstream?

There are some config options mentioned at https://github.com/tomyvi/php-tracks-recorder - but I am not sure if I should fiddle with those. Can you please point me in the right direction?
