### ISSUE TITLE
Change upstream code package

### ISSUE THREAD

**Issue by joeldebruijn** [YunoHost-Apps/owntracks_ynh#25]
### The Wish

Looks like the upstream app code is from an outdated repository.
I would like some features in more recent versions.
To be able to use more recent commands and options provided by another repository (which the developers currently use).

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.1.15
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 0.1~ynh10

### Steps to reproduce

- SSH into virtual server. 
- Try CLI command 'ocat'
- No such command etc

The new place can be found at:
[Repository](https://github.com/owntracks/recorder)

**Comment by CodeShakingSheep** [comment]
As you closed https://github.com/YunoHost-Apps/owntracks_ynh/issues/33 can you please comment on if and if yes when this is planned? I don't really understand what's going on with this package. First the upstream was this very outdated repository and then someone changed it to owntracks frontend. So, now this package is still not functional. Would be great to have an update on that. :pray:
