### ISSUE TITLE
Unusable and no documentation. 

### ISSUE THREAD

**Issue by nomore1007** [YunoHost-Apps/owntracks_ynh#34]
#### Issue
App comes up with blank page. No documentation to find settings to correct. 

#### Context
New install on Yunohost. 

#### How to replicate
Installed from app catalog. Set user.

#### Expectations
Expected it to install and be able to access the web ui. 

####Logs
https://paste.yunohost.org/raw/xelofuyenu

**Comment by tituspijean** [comment]
Consequence of #25 #29
