### ISSUE TITLE
Your app is level 0

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/owntracks_ynh#7]
Hi,

Your app doesn't work on our CI and is currently level 0.
https://ci-apps.yunohost.org/jenkins/job/owntracks%20(Community)/6/consoleFull

Your app will be moved at 'notworking' status by the end of this week, on May, 27 if nothing is done before to make it work.

**Comment by tituspijean** [comment]
As of https://github.com/YunoHost-Apps/owntracks_ynh/commit/f61ece0ba9524350df9c14a0f5f004e4812aeb1d, the app should be working again. @maniackcrudelis, can you add it again to the CI ?

**Comment by maniackcrudelis** [comment]
I do not have any control on the CI.
For your app to be add to the CI, please change the status of the app to `working` in the [community list](https://github.com/YunoHost/apps/blob/master/community.json).
If you're sure that your app is now working.
